# Dockerfile.worker

# Stage 1: Base image with Python and common requirements
FROM python:3.8 AS base

WORKDIR /app
COPY requirements_base.txt .
RUN  pip install -r requirements_base.txt

# Stage 2: Build stage for the worker
FROM base AS worker-builder
COPY requirements_worker.txt .
RUN  pip install -r requirements_worker.txt

# Stage 3: Final image for the worker
FROM worker-builder AS worker
COPY worker_train.py train_flert.py train_bilstm.py /app/

# Set PYTHONUNBUFFERED to 1 to disable output buffering
ENV PYTHONUNBUFFERED=1

CMD ["python", "worker_train.py"]
