# Dockerfile.worker

# Start from the NVIDIA CUDA base image
FROM nvidia/cuda:12.0.0-devel-ubuntu20.04 AS base

# Install Python and any required tools
RUN apt-get update && apt-get install -y python3 python3-pip

# Optional: Set python3 as the default python
RUN ln -s /usr/bin/python3 /usr/local/bin/python


WORKDIR /app
COPY requirements_base.txt .
RUN  pip install -r requirements_base.txt

# Stage 2: Build stage for the worker
FROM base AS worker-builder
COPY requirements_worker.txt .
RUN  pip install -r requirements_worker.txt
RUN python -m spacy download de_core_news_sm


# Stage 3: Final image for the worker
FROM worker-builder AS worker
COPY rulebased /app
COPY worker_predict.py predict.py tool_visuals.py /app/
ENV PYTHONUNBUFFERED=1
CMD ["python", "worker_predict.py"]