class Aktion:
    d = [{"label": "Aktion", "pattern": [{"TEXT": "Vermeidung"}]},
             {"label": "Aktion",
              "pattern": [{"TAG": "VVIZU"}]},
             {"label": "Aktion",
              "pattern": [{"TEXT": "zu"},
                          {"TAG": "VVINF"}]},
         {"label": "Aktion",
          "pattern": [{"TEXT": {"IN": ["Tätigkeit",
                                       "Beitragspflicht",
                                       "Mitwirkungspflicht",
                                       "Angabe",
                                       "Hilfe",
                                       "Erziehungshilfe"]}}]},
         {"label": "Aktion",
          "pattern": [{"TEXT": {"IN": ["Altersrente",
                                        "Arbeitslosengeld I",
                                        "Arbeitslosengeld II",
                                        "Kindergeld",
                                        "Elterngeld",
                                        "Wohngeld",
                                        "Bafög",
                                        "Grundsicherung im Alter",
                                        "Sozialhilfe",
                                        "Krankengeld",
                                        "Mutterschaftsgeld",
                                        "Pflegegeld",
                                        "Erziehungsgeld",
                                        "Baukindergeld",
                                        "Übergangsgeld",
                                        "Betreuungsgeld",
                                        "Wiedereingliederungsgeld",
                                        "Versorgungsausgleich",
                                        "Unfallrente",
                                        "Hinterbliebenenrente",
                                        "Waisenrente",
                                        "Erwerbsminderungsrente",
                                        "Blindenhilfe",
                                        "Bildungsgutschein",
                                        "Kfz-Steuerbefreiung",
                                        "Elternzeit",
                                        "Unterhaltsvorschuss",
                                        "Schüler-BAföG",
                                        "Meister-BAföG",
                                        "Betreuungsunterhalt",
                                        "Mindestunterhalt",
                                        "Landeserziehungsgeld",
                                        "Ausbildungsförderung",
                                        "Integrationshilfe",
                                        "Krankenhilfe",
                                        "Heizkostenzuschuss",
                                        "Kriegsopferfürsorge",
                                        "ElterngeldPlus",
                                        "Betreuungsgeld",
                                        "Übergangsgebührnisse",
                                        "Betriebliche Altersvorsorge",
                                        "Aufstockungsbeträge",
                                        "Heimerziehungskosten",
                                        "Eingliederungshilfe",
                                        "Wohnberechtigungsschein",
                                        "Jugendhilfe",
                                        "Existenzgründungszuschuss",
                                        "Soforthilfe",
                                        "Hilfe zur Pflege",
                                        "Familienpflegezeit"]}}]},

         {"label": "Aktion",
          "pattern": [{"LOWER": {"REGEX": ".*(en|t)$"},
                       "POS": "VERB",
                       "MORPH": {"IS_SUPERSET": ["VerbForm=Part"]}}]},
         {"label": "Aktion",
          "pattern": [{"LOWER": {"REGEX": ".*(en)$"},
                       "POS": "VERB",
                       "MORPH": {"IS_SUPERSET": ["VerbForm=Inf"]}}]}

             ]




