class Datenfeld:
    # Dummy aus Analyse des Dev-splits 20240618
    d = [{"label": "Datenfeld",
          "pattern": [{"TEXT": {"IN": ["Beglaubigung",
                             "Satzung",
                             "Abschrift",
                             "Bescheinigung",
                             "Äußerung",
                             "Änderungen",
                             "Angaben",
                             "Namen",
                             "Vornamen",
                             "Geburtsnamen",
                             "Geburtsort",
                             "Geburtstag",
                             "Wohnsitz",
                             "Staatsangehörigkeit",
                             "Darlegung",
                             "Tatsachen",
                             "Rechtsgebieten",
                             "Tätigkeiten",
                             "Abschluss",
                             "Qualifikation",
                             "Kenntnisse",
                             "Zugriff",
                             "Gewähr",
                             "Firma",
                             "Ort",
                             "Geschäftsanschrift",
                             "Einzugsbereich",
                             "Wortlaut",
                             "Beleg",
                             "Bestätigung",
                             "Satzung",
                             "Urkunden",
                             "Vertretungsmacht",
                             "Daten",
                             "Verlegung",
                             "Unternehmensgegenstand",
                             "Ansprechstelle",
                             "Fingerabdrücke",
                             "Refernznummern",
                             "Schulbildung",
                             "Studium",
                             "Ausbildung",
                             "Beruf",
                             "Sprachkenntnisse",
                             "Teilnahme",
                             "Prüfbericht",
                             "Fahrzeugdaten"]}}]},
         {"label": "Datenfeld",
          "pattern": "deutsche Übersetzung"},
         {"label": "Datenfeld",
          "pattern": "vollständige Anschrift"},
         {"label": "Datenfeld",
          "pattern": "Tag seiner Ausstellung"}]
