class Handlungsgrundlage:
        d = [
                {"label": "Handlungsgrundlage",
                 "pattern": [{"TEXT": "§"},
                             {"TEXT": "§"},
                             {"IS_DIGIT": True},
                             {"TEXT": "bis"},
                             {"IS_DIGIT": True}]},
                {"label": "Handlungsgrundlage",
                 "pattern": [{"TEXT": "§"},
                             {"TEXT": "§"},
                             {"IS_DIGIT": True},
                             {"TEXT": "und"},
                             {"IS_DIGIT": True}]},
                {"label": "Handlungsgrundlage",
                 "pattern": [{"TEXT": "§"},
                             {"TEXT": "§"},
                             {"IS_DIGIT": True},
                             {"TEXT": "bis"},
                             {"IS_DIGIT": True},
                             {"TEXT": "und"},
                             {"IS_DIGIT": True}]},
                {"label": "Handlungsgrundlage",
                 "pattern": [{"TEXT": {"IN": [
                        "Wertpapierhandelsgesetzes", 
                         "Stromsteuergesetzes", 
                         "Altersteilzeitgesetzes", 
                         "Beurkundungsgesetzes", 
                         "Versicherungsaufsichtsgesetzes", 
                         "Entwicklungshelfer-Gesetzes", 
                         "Bundeskindergeldgesetzes", 
                         "Partnerschaftsgesellschaftsgesetzes", 
                         "Einsatz-Weiterverwendungsgesetzes", 
                         "Grundgesetzes", 
                         "Betriebsverfassungsgesetzes", 
                         "Gerichtsverfassungsgesetzes", 
                         "Jugendfreiwilligendienstegesetzes", 
                         "Verwaltungsvollstreckungsgesetzes", 
                         "Bundesberggesetzes", 
                         "Justizentschädigungsgesetzes", 
                         "Statistikregistergesetzes", 
                         "Genossenschaftsgesetzes", 
                         "Beamtenversorgungsgesetzes", 
                         "Abfallgesetzes", 
                         "Personenstandsgesetzes", 
                         "Kraft-Wärme-Kopplungsgesetzes", 
                         "Bundesverfassungsschutzgesetzes", 
                         "Patentgesetzes", 
                         "Bundesausbildungsförderungsgesetzes", 
                         "Bundesversorgungsgesetzes", 
                         "Aufenthaltsgesetzes", 
                         "Asylgesetzes", 
                         "Bundes-Immissionsschutzgesetzes", 
                         "Einführungsgesetzes", 
                         "Asylbewerberleistungsgesetzes", 
                         "Patentkostengesetzes", 
                         "Energiesteuergesetzes", 
                         "Kreditwesengesetzes", 
                         "Justizvergütungsgesetzes", 
                         "Steinkohlefinanzierungsgesetzes", 
                         "Gebrauchsmustergesetzes", 
                         "Eichgesetzes", 
                         "Verwaltungsverfahrensgesetzes", 
                         "Bundesvertriebenengesetzes", 
                         "Transsexuellengesetzes", 
                         "Soldatengesetzes", 
                         "Bundesverfassungsgerichtsgesetzes", 
                         "Hochschulrahmengesetzes", 
                         "Pflanzenschutzgesetzes"
                 ]}}]},
                
        ]

