class Hauptakteur:
    d = [
            # Pattern "Entsorgungsträger" fehlt tatsächlich. Hilfst es hier?
            # {"label": "Hauptakteur",
            #  "pattern": [{"TEXT": "Entsorgungsträger"}]},
            {"label": "Hauptakteur",
             "pattern": [{"TEXT": "öffentlich-rechtlichen"},
                         {"TAG": "NNE"}]},
            {"label": "Hauptakteur",
             "pattern": [{"TEXT": "öffentlich-rechtlichen"},
                         {"TAG": "NN"}]},
            {"label": "Hauptakteur",
             "pattern": [{"TEXT": "öffentlich-rechtlichen"},
                         {"TAG": "NE"}]},
        {"label": "Hauptakteur",
         "pattern": [{"TEXT": {"IN": ["Generalzolldirektion","Eisenbahn-Bundesamt","Zollbediensteten","Erhebungsbeauftragten","Luftfahrt-Bundesamt","Genehmigungsbehörde","Geschäftsführung","Einzugsstelle","Rehabilitierungsbehörde","Wehrersatzbehörde","Standesämtern","Versicherungsunternehmen","Kriegsopferfürsorge","Wirtschaftsprüferkammern","Erhebungsstelle","Handwerkskammer","Zulassungsbehörde","Krankenkasse","Gemeindebehörden","Aufsichtsbehörden","Zertifizierungsstelle","Forstbetriebsverband","IndustrieKammer","Steuerberaterkammern","Erhebungsstellen","Bundeswehr","Urkundsbeamten","Standesamt","Land","Beschwerdesenats","Handelskammern","Amtsgerichte","Markenamt","Landesjustizverwaltung","Beauftragten","Straßenverkehrsbehörden","Gemeindebehörde","Ausländerbehörde","Verbände","Organisationseinheit","Bundesoberbehörde","Aufsichtsbehörde","Landgerichte","Bundesamt","Zollbehörde","Justizbehörde","Unfallversicherungsträger","Bundesanstalt","Sonderungsbehörde","Industriekammern","Genehmigungsbehörden","Verantwortliche","Meldebehörde","Bundesverwaltungsamt","Insolvenzgericht","Krankenhaus","Erlaubnisbehörde","Steuerberaterkammer","Registerbehörde","Jugendamt","Kammer","Pflegekasse","Markttransparenzstelle","Vereinigungen","Patentamt","Bundesgerichtshof","Verwaltungsbehörde","Leistungsträger","Rehabilitationseinrichtung","Demontagebetrieb","Bundesstelle","Grundbuchamt","Anhörungsbehörde","Patentanwaltskammer","Kartellbehörde","Landesjustizverwaltungen","Registergericht"]}}]},
        {"label": "Hauptakteur", "pattern": "Bundesamt für Verfassungsschutz"},
        {"label": "Hauptakteur", "pattern": "Prüfstelle für jugendgefährdende Medien"},
        {"label": "Hauptakteur", "pattern": "Aufsichtsbehörde Aufsichtsbehörde Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "Amt für Ausbildungsförderung"},
        {"label": "Hauptakteur", "pattern": "Kreditanstalt für Wiederaufbau"},
        {"label": "Hauptakteur", "pattern": "Standesamt I in Berlin"},
        {"label": "Hauptakteur", "pattern": "Statistische Bundesamt"},
        {"label": "Hauptakteur", "pattern": "obersten Landesbehörden"},
        {"label": "Hauptakteur", "pattern": "Industrie - und Handelskammer"},
        {"label": "Hauptakteur", "pattern": "Träger der Rentenversicherung"},
        {"label": "Hauptakteur", "pattern": "Bundesanstalt Hauptverwaltung der Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "Bundesanstalt für Landwirtschaft und Ernährung"},
        {"label": "Hauptakteur", "pattern": "Bundesamt für Sicherheit in der Informationstechnik"},
        {"label": "Hauptakteur", "pattern": "Bundesministerium für Wirtschaft und Energie"},
        {"label": "Hauptakteur", "pattern": "Hauptverwaltung der Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "öffentlich-rechtlichen Entsorgungsträger"},
        {"label": "Hauptakteur", "pattern": "Bundesagentur für Arbeit"},
        {"label": "Hauptakteur", "pattern": "Bundesministerium für Verkehr und digitale Infrastruktur"},
        {"label": "Hauptakteur", "pattern": "Pflegeberater Pflegeberaterin"},
        {"label": "Hauptakteur", "pattern": "zuständigen Behörde"},
        {"label": "Hauptakteur", "pattern": "Standesamt I"},
        {"label": "Hauptakteur", "pattern": "Aufsichtsbehörde Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "staatlichen Gemeinschaft"},
        {"label": "Hauptakteur", "pattern": "Industrie - und Handelskammern"},
        {"label": "Hauptakteur", "pattern": "Agentur für Arbeit"},
        {"label": "Hauptakteur", "pattern": "Markttransparenzstelle für Kraftstoffe"},
        {"label": "Hauptakteur", "pattern": "zuständigen Behörde Behörde"},
        {"label": "Hauptakteur", "pattern": "Bundesanstalt Deutschen Bundesbank"},
        {"label": "Hauptakteur", "pattern": "Industriekammern Handelskammern"},
        {"label": "Hauptakteur", "pattern": "Julius Kühn-Institut"},
        {"label": "Hauptakteur", "pattern": "Industrie - und Handelskammer Stelle"},
        {"label": "Hauptakteur", "pattern": "Deutschen Patent - und Markenamtes"},
        {"label": "Hauptakteur", "pattern": "Bundesamt für Migration und Flüchtlinge"},
        {"label": "Hauptakteur", "pattern": "Träger der öffentlichen Jugendhilfe"},
        {"label": "Hauptakteur", "pattern": "Bundesamt für Seeschifffahrt und Hydrographie"}
        ]

