class Signalwort:
    d = [{"label": "Signalwort", "pattern": [{"LEMMA": "sollen"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "gelten"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "genügen"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "ermöglichen"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "rechtfertigen"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "bedürfen"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "freiwillig"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "maßgeblich"}]},
         {"label": "Signalwort", "pattern": [{"LEMMA": "verpflichten"}]},
         {"label": "Signalwort",
          "pattern": [{"LEMMA": "sein", "OP": "?"},
                      {"LOWER": "auf"},
                      {"TEXT": {"IN": ["Antrag", "Verlangen"]}}]},
         {"label": "Signalwort",
          "pattern": [{"LOWER": "mit"},
                      {"TEXT": "Zustimmung"}]},
         {"label": "Signalwort",
          "pattern": [{"LOWER": "auf"},
                      {"TEXT": "Wunsch"}]},
         {"label": "Signalwort",
          "pattern": [{"LOWER": "im"},
                      {"TEXT": "Einzelfall"},
                      {"LEMMA": "können"}]},
         {"label": "Signalwort",
          "pattern": [{"LOWER": "von"},
                      {"TEXT": "Amts"},
                      {"TEXT": "wegen"}]},
         {"label": "Signalwort", "pattern": "notwendig"},
         {"label": "Signalwort", "pattern": "Mitteilungspflicht"},
         {"label": "Signalwort", "pattern": "Antragsberechtigt"},
         {"label": "Signalwort", "pattern": "Befähigung"},
         {"label": "Signalwort", "pattern": "Recht"},
         {"label": "Signalwort", "pattern": "Rechtsnachfolge"},
         {"label": "Signalwort", "pattern": "Anspruch"},
         {"label": "Signalwort", "pattern": "Regel"},
         {"label": "Signalwort", "pattern": "maßgebend"},
         {"label": "Signalwort", "pattern": "unzulässig"},
         {"label": "Signalwort", "pattern": "berechtigt"},
         {"label": "Signalwort", "pattern": "zulässig"},
         {"label": "Signalwort", "pattern": "unzulässig"},
         {"label": "Signalwort", "pattern": "unwirksam"},
         {"label": "Signalwort", "pattern": "ausgeschlossen"},
         {"label": "Signalwort", "pattern": "angemessen"},
         {"label": "Signalwort", "pattern": "Einvernehmens"}
         ]
