# Stage 1: Base image with Python and common requirements
FROM python:3.8 AS base
WORKDIR /app
COPY requirements_base.txt .
RUN  pip install -r requirements_base.txt

# Stage 2: Build stage for the server
FROM base AS server-builder
RUN apt-get update && apt-get install -y tesseract-ocr-deu
RUN apt-get update && apt-get install -y poppler-utils
COPY requirements_server.txt .
RUN pip install -r requirements_server.txt
RUN pip install gunicorn

# Stage 3: Final image for the server
FROM server-builder AS server

# For logrotate, cron and their configuration
RUN apt-get update && apt-get install -y logrotate cron

COPY logrotate.conf /etc/logrotate.d/HIL_prototyp
RUN chmod 0644 /etc/logrotate.d/HIL_prototyp

COPY crontab /etc/cron.d/HIL_prototyp-cron
RUN chmod 0644 /etc/cron.d/HIL_prototyp-cron

COPY custom-logrotate.sh /usr/local/bin/custom-logrotate.sh
RUN chmod +x /usr/local/bin/custom-logrotate.sh

RUN crontab /etc/cron.d/HIL_prototyp-cron

# Copy application code
COPY handlers /app/handlers
COPY server.py /app/

# Expose the port
EXPOSE 8070

# Start cron and the application
CMD cron && gunicorn --workers 4 --threads 2  -b 0.0.0.0:8070 server:app
